[package]
name = "smart_contract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9.1"
bindgen = "0.59.1"
env_logger = "0.9.0"

[lib]
crate-type = ["cdylib", "lib"]